---
apiVersion: v1
kind: Service
metadata:
  name: nodered
  namespace: telemetry
spec:
  selector:
    app: nodered
  ports:
    - port: 1880
      targetPort: 1880
      nodePort: 1880
      name: http
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered
  namespace: telemetry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodered
  template:
    metadata:
      labels:
        app: nodered
    spec:
      containers:
        - name: nodered
          image: nodered/node-red:latest
          ports:
            - containerPort: 1880
